### ISSUE TITLE
Syntax error when executing mysql.intial.sql

### ISSUE THREAD

**Issue by ychaouche** [teonsystems/roundcube-plugin-smart-autocomplete#2] opened 2016-08-15 13:21 UTC
```
root@messagerie[CHROOT][10.10.10.20] /var/www/roundcubemail-1.1.4/plugins/smart_autocomplete/SQL # mysql roundcube -ubackup -p < mysql.initial.sql 
Enter password: 
ERROR 1064 (42000) at line 11: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 14
root@messagerie[CHROOT][10.10.10.20] /var/www/roundcubemail-1.1.4/plugins/smart_autocomplete/SQL # 
```
The file has one ";" troublemaker. It is fixed in the pull request #1

**Comment by bostjan** [comment] 2016-08-15 19:49
Duplicate of #1.

**Closed by bostjan** 2016-08-15 19:49 UTC
Labels: duplicate
